spring:
  datasource:
    url: ${DB_TRADE_URL}
    username: ${DB_TRADE_USER}
    password: ${DB_TRADE_PASSWORD}
  jpa:
    show-sql: false

logging:
  level:
    ve.com.vettal.trademarketing: INFO
    org.hibernate.SQL: WARN
